version: "2.3"

services:
  db:
    container_name: homely_cloud_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
      TZ: 'Etc/UTC'
    ports:
      - "3306:3306"
    volumes:
      - homely-cloud-db:/var/lib/mysql

  localstack:
    container_name: localstack
    image: localstack/localstack
    environment:
      - "SERVICES=sqs,kinesis,apigateway,lambda,s3,ses,kms,sns"
      - "DEFAULT_REGION=eu-west-1"
      - "HOSTNAME=localhost"
      - "HOSTNAME_EXTERNAL=localhost"
      - "USE_SSL=false"
      - "DATA_DIR=${LOCALSTACK_DATA_DIR:-/tmp/localstack/data}"
    ports:
      - "4567-4599:4567-4599"
      - "8080:8080"


volumes:
  homely-cloud-db: