AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Homely cloud APIs

Globals:
  Function:
    Timeout: 3

Parameters:
  NodeEnv:
    Type: String
  NodeRuntime:
    Type: String
    Default: 'nodejs12.x'

Resources:
  HomelyCloudApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: homely-cloud-dev
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub "{{resolve:secretsmanager:devHomelyCognitoArn}}"

  ViewConfigFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/controllers/view-config.controller
      Runtime: nodejs12.x
      Timeout: 900
      Environment:
        Variables:
          NODE_ENV: !Ref 'NodeEnv'
      Events:
        ViewConfig:
          Type: Api
          Properties:
            Path: /config
            Method: get
            RestApiId: !Ref 'HomelyCloudApiGateway'
#            Auth:
#              Authorizer: CognitoAuthorizer

  ServiceRegsitrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/controllers/server-registration.controller
      Runtime: nodejs12.x
      Timeout: 900
      Environment:
        Variables:
          NODE_ENV: !Ref 'NodeEnv'
      Events:
        ServiceRegistration:
          Type: Api
          Properties:
            Path: /register-on-premise
            Method: post
            RestApiId: !Ref 'HomelyCloudApiGateway'

  PairServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/controllers/pair-server.controller
      Runtime: nodejs12.x
      Timeout: 900
      Environment:
        Variables:
          NODE_ENV: !Ref 'NodeEnv'
      Events:
        HomeRegistration:
          Type: Api
          Properties:
            Path: /pair-server
            Method: post
            RestApiId: !Ref 'HomelyCloudApiGateway'
#            Auth:
#              Authorizer: CognitoAuthorizer